///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SETUP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SETUPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3ba399e0-e261-4256-bad3-b90c9aa68b0c")]
    public partial class SETUPRepository : RepoGenBaseFolder
    {
        static SETUPRepository instance = new SETUPRepository();
        SETUPRepositoryFolders.FirstRunDialogAppFolder _firstrundialog;
        SETUPRepositoryFolders.StartDialogAppFolder _startdialog;
        SETUPRepositoryFolders.OpenProjectAppFolder _openproject;
        SETUPRepositoryFolders.ProcessMonitorAppFolder _processmonitor;
        SETUPRepositoryFolders.MenuFileAppFolder _menufile;
        SETUPRepositoryFolders.MenuCreateAppFolder _menucreate;
        SETUPRepositoryFolders.ProjectWindowAppFolder _projectwindow;
        SETUPRepositoryFolders.ListAppFolder _list;
        SETUPRepositoryFolders.QMessageBox1AppFolder _qmessagebox1;
        SETUPRepositoryFolders.QMessageBox2AppFolder _qmessagebox2;
        SETUPRepositoryFolders.QMessageBox3AppFolder _qmessagebox3;
        SETUPRepositoryFolders.FileReplaceDialogAppFolder _filereplacedialog;

        /// <summary>
        /// Gets the singleton class instance representing the SETUPRepository element repository.
        /// </summary>
        [RepositoryFolder("3ba399e0-e261-4256-bad3-b90c9aa68b0c")]
        public static SETUPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SETUPRepository() 
            : base("SETUPRepository", "/", null, 0, false, "3ba399e0-e261-4256-bad3-b90c9aa68b0c", ".\\RepositoryImages\\SETUPRepository3ba399e0.rximgres")
        {
            _firstrundialog = new SETUPRepositoryFolders.FirstRunDialogAppFolder(this);
            _startdialog = new SETUPRepositoryFolders.StartDialogAppFolder(this);
            _openproject = new SETUPRepositoryFolders.OpenProjectAppFolder(this);
            _processmonitor = new SETUPRepositoryFolders.ProcessMonitorAppFolder(this);
            _menufile = new SETUPRepositoryFolders.MenuFileAppFolder(this);
            _menucreate = new SETUPRepositoryFolders.MenuCreateAppFolder(this);
            _projectwindow = new SETUPRepositoryFolders.ProjectWindowAppFolder(this);
            _list = new SETUPRepositoryFolders.ListAppFolder(this);
            _qmessagebox1 = new SETUPRepositoryFolders.QMessageBox1AppFolder(this);
            _qmessagebox2 = new SETUPRepositoryFolders.QMessageBox2AppFolder(this);
            _qmessagebox3 = new SETUPRepositoryFolders.QMessageBox3AppFolder(this);
            _filereplacedialog = new SETUPRepositoryFolders.FileReplaceDialogAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3ba399e0-e261-4256-bad3-b90c9aa68b0c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FirstRunDialog folder.
        /// </summary>
        [RepositoryFolder("3d7e668e-a424-46c2-9b4d-136422dbd4fd")]
        public virtual SETUPRepositoryFolders.FirstRunDialogAppFolder FirstRunDialog
        {
            get { return _firstrundialog; }
        }

        /// <summary>
        /// The StartDialog folder.
        /// </summary>
        [RepositoryFolder("6d523494-2aa9-4cf7-81dc-537ed78f9066")]
        public virtual SETUPRepositoryFolders.StartDialogAppFolder StartDialog
        {
            get { return _startdialog; }
        }

        /// <summary>
        /// The OpenProject folder.
        /// </summary>
        [RepositoryFolder("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
        public virtual SETUPRepositoryFolders.OpenProjectAppFolder OpenProject
        {
            get { return _openproject; }
        }

        /// <summary>
        /// The ProcessMonitor folder.
        /// </summary>
        [RepositoryFolder("170111f4-17f1-4f8d-a4d3-2c283360b1a0")]
        public virtual SETUPRepositoryFolders.ProcessMonitorAppFolder ProcessMonitor
        {
            get { return _processmonitor; }
        }

        /// <summary>
        /// The MenuFile folder.
        /// </summary>
        [RepositoryFolder("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
        public virtual SETUPRepositoryFolders.MenuFileAppFolder MenuFile
        {
            get { return _menufile; }
        }

        /// <summary>
        /// The MenuCreate folder.
        /// </summary>
        [RepositoryFolder("a43e1b77-f975-48e4-884e-80edb651986f")]
        public virtual SETUPRepositoryFolders.MenuCreateAppFolder MenuCreate
        {
            get { return _menucreate; }
        }

        /// <summary>
        /// The ProjectWindow folder.
        /// </summary>
        [RepositoryFolder("e449124e-0db5-4931-99c4-8479aabbe103")]
        public virtual SETUPRepositoryFolders.ProjectWindowAppFolder ProjectWindow
        {
            get { return _projectwindow; }
        }

        /// <summary>
        /// The List folder.
        /// </summary>
        [RepositoryFolder("affa1615-928c-4438-be53-4cb2ac4a956c")]
        public virtual SETUPRepositoryFolders.ListAppFolder List
        {
            get { return _list; }
        }

        /// <summary>
        /// The QMessageBox1 folder.
        /// </summary>
        [RepositoryFolder("4211b6b2-cfdf-40e6-ab93-b95b311f0025")]
        public virtual SETUPRepositoryFolders.QMessageBox1AppFolder QMessageBox1
        {
            get { return _qmessagebox1; }
        }

        /// <summary>
        /// The QMessageBox2 folder.
        /// </summary>
        [RepositoryFolder("2d5450a1-53df-48fb-8f2a-6a93bc234f85")]
        public virtual SETUPRepositoryFolders.QMessageBox2AppFolder QMessageBox2
        {
            get { return _qmessagebox2; }
        }

        /// <summary>
        /// The QMessageBox3 folder.
        /// </summary>
        [RepositoryFolder("6d4612c9-8d02-49c8-b61f-f6da99934401")]
        public virtual SETUPRepositoryFolders.QMessageBox3AppFolder QMessageBox3
        {
            get { return _qmessagebox3; }
        }

        /// <summary>
        /// The FileReplaceDialog folder.
        /// </summary>
        [RepositoryFolder("ec5d04e8-b39c-43ef-aa9e-dba9bb65a9fe")]
        public virtual SETUPRepositoryFolders.FileReplaceDialogAppFolder FileReplaceDialog
        {
            get { return _filereplacedialog; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SETUPRepositoryFolders
    {
        /// <summary>
        /// The FirstRunDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("3d7e668e-a424-46c2-9b4d-136422dbd4fd")]
        public partial class FirstRunDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pathInfo;
            RepoItemInfo _okbtnInfo;

            /// <summary>
            /// Creates a new FirstRunDialog  folder.
            /// </summary>
            public FirstRunDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FirstRunDialog", "/form[@name='FirstRunDialog']", parentFolder, 30000, null, true, "3d7e668e-a424-46c2-9b4d-136422dbd4fd", "")
            {
                _pathInfo = new RepoItemInfo(this, "Path", "text[@name='Path' and @basetype='QLineEdit']", "", 30000, null, "b6b24b17-dcd7-45e0-a921-fa36648e2ded");
                _okbtnInfo = new RepoItemInfo(this, "OKBtn", "?/?/button[@text='OK']", "", 30000, null, "3c4293d8-0dc5-4126-96b3-1804c70141d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d7e668e-a424-46c2-9b4d-136422dbd4fd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d7e668e-a424-46c2-9b4d-136422dbd4fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("b6b24b17-dcd7-45e0-a921-fa36648e2ded")]
            public virtual Ranorex.Text Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("b6b24b17-dcd7-45e0-a921-fa36648e2ded")]
            public virtual RepoItemInfo PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }

            /// <summary>
            /// The OKBtn item.
            /// </summary>
            [RepositoryItem("3c4293d8-0dc5-4126-96b3-1804c70141d1")]
            public virtual Ranorex.Button OKBtn
            {
                get
                {
                    return _okbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKBtn item info.
            /// </summary>
            [RepositoryItemInfo("3c4293d8-0dc5-4126-96b3-1804c70141d1")]
            public virtual RepoItemInfo OKBtnInfo
            {
                get
                {
                    return _okbtnInfo;
                }
            }
        }

        /// <summary>
        /// The StartDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("6d523494-2aa9-4cf7-81dc-537ed78f9066")]
        public partial class StartDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createnewprojectInfo;
            RepoItemInfo _openprojectInfo;

            /// <summary>
            /// Creates a new StartDialog  folder.
            /// </summary>
            public StartDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StartDialog", "/form[@type='StartDialog']", parentFolder, 30000, null, true, "6d523494-2aa9-4cf7-81dc-537ed78f9066", "")
            {
                _createnewprojectInfo = new RepoItemInfo(this, "CreateNewProject", "button[@text='Create New Project']", "", 30000, null, "b84202c0-a94f-4d6c-b570-50395d7d3a56");
                _openprojectInfo = new RepoItemInfo(this, "OpenProject", "button[@text='Open Project']", "", 30000, null, "373ec341-b08f-4633-b1d1-c8944acea685");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d523494-2aa9-4cf7-81dc-537ed78f9066")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d523494-2aa9-4cf7-81dc-537ed78f9066")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNewProject item.
            /// </summary>
            [RepositoryItem("b84202c0-a94f-4d6c-b570-50395d7d3a56")]
            public virtual Ranorex.Button CreateNewProject
            {
                get
                {
                    return _createnewprojectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNewProject item info.
            /// </summary>
            [RepositoryItemInfo("b84202c0-a94f-4d6c-b570-50395d7d3a56")]
            public virtual RepoItemInfo CreateNewProjectInfo
            {
                get
                {
                    return _createnewprojectInfo;
                }
            }

            /// <summary>
            /// The OpenProject item.
            /// </summary>
            [RepositoryItem("373ec341-b08f-4633-b1d1-c8944acea685")]
            public virtual Ranorex.Button OpenProject
            {
                get
                {
                    return _openprojectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenProject item info.
            /// </summary>
            [RepositoryItemInfo("373ec341-b08f-4633-b1d1-c8944acea685")]
            public virtual RepoItemInfo OpenProjectInfo
            {
                get
                {
                    return _openprojectInfo;
                }
            }
        }

        /// <summary>
        /// The OpenProjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
        public partial class OpenProjectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _previouslocationsInfo;
            RepoItemInfo _text41477Info;
            RepoItemInfo _text1148Info;
            RepoItemInfo _openbtnInfo;
            RepoItemInfo _combobox1136Info;

            /// <summary>
            /// Creates a new OpenProject  folder.
            /// </summary>
            public OpenProjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenProject", "/form[@title='Open Project']", parentFolder, 30000, null, true, "7846dc71-9b6d-4c80-bfef-f400f97cb875", "")
            {
                _previouslocationsInfo = new RepoItemInfo(this, "PreviousLocations", "element[@class='WorkerW']//progressbar/toolbar[@class='ToolbarWindow32']/button[@text='Previous locations']", "", 30000, null, "a3cbd65d-a8c7-4c98-98f7-675338fadbb3");
                _text41477Info = new RepoItemInfo(this, "Text41477", "element[@class='WorkerW']//combobox[@controlid='41477']/text[@controlid='41477']", "", 30000, null, "56856e32-e757-4bdf-9ed2-b3b746cd4d30");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", "", 30000, null, "cd7cda52-a63c-4613-8020-050dcfad69cd");
                _openbtnInfo = new RepoItemInfo(this, "OpenBtn", "button[@text='&Open']", "", 30000, null, "288726d3-b25b-403d-93ae-9763d0cc4a8e");
                _combobox1136Info = new RepoItemInfo(this, "ComboBox1136", "combobox[@controlid='1136']", "", 30000, null, "2cf381a7-efba-44b0-b095-aefe916b8eba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PreviousLocations item.
            /// </summary>
            [RepositoryItem("a3cbd65d-a8c7-4c98-98f7-675338fadbb3")]
            public virtual Ranorex.Button PreviousLocations
            {
                get
                {
                    return _previouslocationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PreviousLocations item info.
            /// </summary>
            [RepositoryItemInfo("a3cbd65d-a8c7-4c98-98f7-675338fadbb3")]
            public virtual RepoItemInfo PreviousLocationsInfo
            {
                get
                {
                    return _previouslocationsInfo;
                }
            }

            /// <summary>
            /// The Text41477 item.
            /// </summary>
            [RepositoryItem("56856e32-e757-4bdf-9ed2-b3b746cd4d30")]
            public virtual Ranorex.Text Text41477
            {
                get
                {
                    return _text41477Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text41477 item info.
            /// </summary>
            [RepositoryItemInfo("56856e32-e757-4bdf-9ed2-b3b746cd4d30")]
            public virtual RepoItemInfo Text41477Info
            {
                get
                {
                    return _text41477Info;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("cd7cda52-a63c-4613-8020-050dcfad69cd")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("cd7cda52-a63c-4613-8020-050dcfad69cd")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The OpenBtn item.
            /// </summary>
            [RepositoryItem("288726d3-b25b-403d-93ae-9763d0cc4a8e")]
            public virtual Ranorex.Button OpenBtn
            {
                get
                {
                    return _openbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenBtn item info.
            /// </summary>
            [RepositoryItemInfo("288726d3-b25b-403d-93ae-9763d0cc4a8e")]
            public virtual RepoItemInfo OpenBtnInfo
            {
                get
                {
                    return _openbtnInfo;
                }
            }

            /// <summary>
            /// The ComboBox1136 item.
            /// </summary>
            [RepositoryItem("2cf381a7-efba-44b0-b095-aefe916b8eba")]
            public virtual Ranorex.ComboBox ComboBox1136
            {
                get
                {
                    return _combobox1136Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1136 item info.
            /// </summary>
            [RepositoryItemInfo("2cf381a7-efba-44b0-b095-aefe916b8eba")]
            public virtual RepoItemInfo ComboBox1136Info
            {
                get
                {
                    return _combobox1136Info;
                }
            }
        }

        /// <summary>
        /// The ProcessMonitorAppFolder folder.
        /// </summary>
        [RepositoryFolder("170111f4-17f1-4f8d-a4d3-2c283360b1a0")]
        public partial class ProcessMonitorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _doneInfo;

            /// <summary>
            /// Creates a new ProcessMonitor  folder.
            /// </summary>
            public ProcessMonitorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProcessMonitor", "/form[@name='processMonitor' and @basetype='QDialog']", parentFolder, 30000, null, true, "170111f4-17f1-4f8d-a4d3-2c283360b1a0", "")
            {
                _doneInfo = new RepoItemInfo(this, "Done", "button[@text='Done']", "", 30000, null, "7494106d-8e9e-4efb-a465-63486041b2e2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("170111f4-17f1-4f8d-a4d3-2c283360b1a0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("170111f4-17f1-4f8d-a4d3-2c283360b1a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Done item.
            /// </summary>
            [RepositoryItem("7494106d-8e9e-4efb-a465-63486041b2e2")]
            public virtual Ranorex.Button Done
            {
                get
                {
                    return _doneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Done item info.
            /// </summary>
            [RepositoryItemInfo("7494106d-8e9e-4efb-a465-63486041b2e2")]
            public virtual RepoItemInfo DoneInfo
            {
                get
                {
                    return _doneInfo;
                }
            }
        }

        /// <summary>
        /// The MenuFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
        public partial class MenuFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _recentprojectInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new MenuFile  folder.
            /// </summary>
            public MenuFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuFile", "/contextmenu[@name='menuFile']", parentFolder, 30000, null, true, "ab54eb33-74a5-4a50-bb2a-e0867116844b", "")
            {
                _createInfo = new RepoItemInfo(this, "Create", "menuitem[@name='menuCreate']", "", 30000, null, "4f6f4144-7c40-4d24-900c-99b417e20777");
                _openInfo = new RepoItemInfo(this, "Open", "menuitem[@name='actOpen']", "", 30000, null, "a1980d2b-d26c-4e3f-9d96-bff6c7081d5d");
                _recentprojectInfo = new RepoItemInfo(this, "RecentProject", "menuitem[@name='menuRecent']", "", 30000, null, "81af665a-9516-4cd6-8d39-3d820e75e664");
                _closeInfo = new RepoItemInfo(this, "Close", "menuitem[@name='actClose']", "", 30000, null, "10f95e5f-6eaa-4172-9cb9-21dfb41eeb0d");
                _exitInfo = new RepoItemInfo(this, "Exit", "menuitem[@name='actExit']", "", 30000, null, "723961ff-7215-4d14-b8b7-c5d03996a984");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Create item.
            /// </summary>
            [RepositoryItem("4f6f4144-7c40-4d24-900c-99b417e20777")]
            public virtual Ranorex.MenuItem Create
            {
                get
                {
                    return _createInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Create item info.
            /// </summary>
            [RepositoryItemInfo("4f6f4144-7c40-4d24-900c-99b417e20777")]
            public virtual RepoItemInfo CreateInfo
            {
                get
                {
                    return _createInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("a1980d2b-d26c-4e3f-9d96-bff6c7081d5d")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("a1980d2b-d26c-4e3f-9d96-bff6c7081d5d")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RecentProject item.
            /// </summary>
            [RepositoryItem("81af665a-9516-4cd6-8d39-3d820e75e664")]
            public virtual Ranorex.MenuItem RecentProject
            {
                get
                {
                    return _recentprojectInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The RecentProject item info.
            /// </summary>
            [RepositoryItemInfo("81af665a-9516-4cd6-8d39-3d820e75e664")]
            public virtual RepoItemInfo RecentProjectInfo
            {
                get
                {
                    return _recentprojectInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("10f95e5f-6eaa-4172-9cb9-21dfb41eeb0d")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("10f95e5f-6eaa-4172-9cb9-21dfb41eeb0d")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("723961ff-7215-4d14-b8b7-c5d03996a984")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("723961ff-7215-4d14-b8b7-c5d03996a984")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The MenuCreateAppFolder folder.
        /// </summary>
        [RepositoryFolder("a43e1b77-f975-48e4-884e-80edb651986f")]
        public partial class MenuCreateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createprojectInfo;

            /// <summary>
            /// Creates a new MenuCreate  folder.
            /// </summary>
            public MenuCreateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuCreate", "/contextmenu[@name='menuCreate']", parentFolder, 30000, null, true, "a43e1b77-f975-48e4-884e-80edb651986f", "")
            {
                _createprojectInfo = new RepoItemInfo(this, "CreateProject", "menuitem[@name~'actCreate']", "", 30000, null, "d41331cf-a9a2-41aa-b6c7-eb2e6e601102");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a43e1b77-f975-48e4-884e-80edb651986f")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a43e1b77-f975-48e4-884e-80edb651986f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateProject item.
            /// </summary>
            [RepositoryItem("d41331cf-a9a2-41aa-b6c7-eb2e6e601102")]
            public virtual Ranorex.MenuItem CreateProject
            {
                get
                {
                    return _createprojectInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CreateProject item info.
            /// </summary>
            [RepositoryItemInfo("d41331cf-a9a2-41aa-b6c7-eb2e6e601102")]
            public virtual RepoItemInfo CreateProjectInfo
            {
                get
                {
                    return _createprojectInfo;
                }
            }
        }

        /// <summary>
        /// The ProjectWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("e449124e-0db5-4931-99c4-8479aabbe103")]
        public partial class ProjectWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;

            /// <summary>
            /// Creates a new ProjectWindow  folder.
            /// </summary>
            public ProjectWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjectWindow", "/form[@name~'ProjectWindow' and @basetype='QMainWindow']", parentFolder, 30000, null, true, "e449124e-0db5-4931-99c4-8479aabbe103", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "element[@type='ui::MenuBar']/?/?/menuitem[@text='File' and @type='QAction']", "", 30000, null, "7f3bc8e5-16d5-4d28-af2f-712ec810848f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e449124e-0db5-4931-99c4-8479aabbe103")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e449124e-0db5-4931-99c4-8479aabbe103")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("7f3bc8e5-16d5-4d28-af2f-712ec810848f")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("7f3bc8e5-16d5-4d28-af2f-712ec810848f")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }
        }

        /// <summary>
        /// The ListAppFolder folder.
        /// </summary>
        [RepositoryFolder("affa1615-928c-4438-be53-4cb2ac4a956c")]
        public partial class ListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _allfilesInfo;

            /// <summary>
            /// Creates a new List  folder.
            /// </summary>
            public ListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("List", "/list[@controlid='1000']", parentFolder, 30000, null, true, "affa1615-928c-4438-be53-4cb2ac4a956c", "")
            {
                _allfilesInfo = new RepoItemInfo(this, "AllFiles", "listitem[@text~'All']", "", 30000, null, "43dc5d30-1806-4e09-9b09-a08a72cdf0c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("affa1615-928c-4438-be53-4cb2ac4a956c")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("affa1615-928c-4438-be53-4cb2ac4a956c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllFiles item.
            /// </summary>
            [RepositoryItem("43dc5d30-1806-4e09-9b09-a08a72cdf0c3")]
            public virtual Ranorex.ListItem AllFiles
            {
                get
                {
                    return _allfilesInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AllFiles item info.
            /// </summary>
            [RepositoryItemInfo("43dc5d30-1806-4e09-9b09-a08a72cdf0c3")]
            public virtual RepoItemInfo AllFilesInfo
            {
                get
                {
                    return _allfilesInfo;
                }
            }
        }

        /// <summary>
        /// The QMessageBox1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4211b6b2-cfdf-40e6-ab93-b95b311f0025")]
        public partial class QMessageBox1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nobtnInfo;
            RepoItemInfo _yesbtnInfo;

            /// <summary>
            /// Creates a new QMessageBox1  folder.
            /// </summary>
            public QMessageBox1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("QMessageBox1", "/form[@windowstyle='Tiled, DialogFrame, ClipChildren, ClipSiblings, Visible, PopupWindow' and @type='QMessageBox']", parentFolder, 30000, null, true, "4211b6b2-cfdf-40e6-ab93-b95b311f0025", "")
            {
                _nobtnInfo = new RepoItemInfo(this, "NoBtn", "container[@name='qt_msgbox_buttonbox']/button[@text='&No']", "", 30000, null, "dfad96b3-2c78-4303-b74f-bc22c11a4a2f");
                _yesbtnInfo = new RepoItemInfo(this, "YesBtn", "?/?/button[@text='&Yes']", "", 30000, null, "cd3a15a0-9791-429e-9ce0-22802d56b011");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4211b6b2-cfdf-40e6-ab93-b95b311f0025")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4211b6b2-cfdf-40e6-ab93-b95b311f0025")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NoBtn item.
            /// </summary>
            [RepositoryItem("dfad96b3-2c78-4303-b74f-bc22c11a4a2f")]
            public virtual Ranorex.Button NoBtn
            {
                get
                {
                    return _nobtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NoBtn item info.
            /// </summary>
            [RepositoryItemInfo("dfad96b3-2c78-4303-b74f-bc22c11a4a2f")]
            public virtual RepoItemInfo NoBtnInfo
            {
                get
                {
                    return _nobtnInfo;
                }
            }

            /// <summary>
            /// The YesBtn item.
            /// </summary>
            [RepositoryItem("cd3a15a0-9791-429e-9ce0-22802d56b011")]
            public virtual Ranorex.Button YesBtn
            {
                get
                {
                    return _yesbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesBtn item info.
            /// </summary>
            [RepositoryItemInfo("cd3a15a0-9791-429e-9ce0-22802d56b011")]
            public virtual RepoItemInfo YesBtnInfo
            {
                get
                {
                    return _yesbtnInfo;
                }
            }
        }

        /// <summary>
        /// The QMessageBox2AppFolder folder.
        /// </summary>
        [RepositoryFolder("2d5450a1-53df-48fb-8f2a-6a93bc234f85")]
        public partial class QMessageBox2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closebtnInfo;

            /// <summary>
            /// Creates a new QMessageBox2  folder.
            /// </summary>
            public QMessageBox2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("QMessageBox2", "/form[@windowstyle='Tiled, DialogFrame, ClipChildren, ClipSiblings, Visible, PopupWindow' and @accessiblerole='Client']", parentFolder, 30000, null, true, "2d5450a1-53df-48fb-8f2a-6a93bc234f85", "")
            {
                _closebtnInfo = new RepoItemInfo(this, "CloseBtn", "?/?/button[@accessiblename='Close']", "", 30000, null, "3e66b093-f26a-4011-908b-4fd6d28571f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2d5450a1-53df-48fb-8f2a-6a93bc234f85")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2d5450a1-53df-48fb-8f2a-6a93bc234f85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseBtn item.
            /// </summary>
            [RepositoryItem("3e66b093-f26a-4011-908b-4fd6d28571f3")]
            public virtual Ranorex.Button CloseBtn
            {
                get
                {
                    return _closebtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseBtn item info.
            /// </summary>
            [RepositoryItemInfo("3e66b093-f26a-4011-908b-4fd6d28571f3")]
            public virtual RepoItemInfo CloseBtnInfo
            {
                get
                {
                    return _closebtnInfo;
                }
            }
        }

        /// <summary>
        /// The QMessageBox3AppFolder folder.
        /// </summary>
        [RepositoryFolder("6d4612c9-8d02-49c8-b61f-f6da99934401")]
        public partial class QMessageBox3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbtnInfo;

            /// <summary>
            /// Creates a new QMessageBox3  folder.
            /// </summary>
            public QMessageBox3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("QMessageBox3", "/form[@type='QMessageBox']", parentFolder, 30000, null, true, "6d4612c9-8d02-49c8-b61f-f6da99934401", "")
            {
                _okbtnInfo = new RepoItemInfo(this, "OKBtn", "container[@name='qt_msgbox_buttonbox']/button[@text='OK']", "", 30000, null, "99f71b56-902f-4ccd-a68e-edcf80900231");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d4612c9-8d02-49c8-b61f-f6da99934401")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d4612c9-8d02-49c8-b61f-f6da99934401")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKBtn item.
            /// </summary>
            [RepositoryItem("99f71b56-902f-4ccd-a68e-edcf80900231")]
            public virtual Ranorex.Button OKBtn
            {
                get
                {
                    return _okbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKBtn item info.
            /// </summary>
            [RepositoryItemInfo("99f71b56-902f-4ccd-a68e-edcf80900231")]
            public virtual RepoItemInfo OKBtnInfo
            {
                get
                {
                    return _okbtnInfo;
                }
            }
        }

        /// <summary>
        /// The FileReplaceDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("ec5d04e8-b39c-43ef-aa9e-dba9bb65a9fe")]
        public partial class FileReplaceDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _replaceallbtnInfo;
            RepoItemInfo _skipallbtnInfo;

            /// <summary>
            /// Creates a new FileReplaceDialog  folder.
            /// </summary>
            public FileReplaceDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileReplaceDialog", "/form[@name='FileReplaceDialog']", parentFolder, 30000, null, true, "ec5d04e8-b39c-43ef-aa9e-dba9bb65a9fe", "")
            {
                _replaceallbtnInfo = new RepoItemInfo(this, "ReplaceAllBtn", "button[@name='replaceAll' and @type='QPushButton']", "", 30000, null, "15d1e663-2a17-44a2-9326-6dafd3bcbee0");
                _skipallbtnInfo = new RepoItemInfo(this, "SkipAllBtn", "button[@name='skipAll' and @type='QPushButton']", "", 30000, null, "7f2482c8-bd50-4c50-aff9-a6fce719c682");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec5d04e8-b39c-43ef-aa9e-dba9bb65a9fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec5d04e8-b39c-43ef-aa9e-dba9bb65a9fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReplaceAllBtn item.
            /// </summary>
            [RepositoryItem("15d1e663-2a17-44a2-9326-6dafd3bcbee0")]
            public virtual Ranorex.Button ReplaceAllBtn
            {
                get
                {
                    return _replaceallbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReplaceAllBtn item info.
            /// </summary>
            [RepositoryItemInfo("15d1e663-2a17-44a2-9326-6dafd3bcbee0")]
            public virtual RepoItemInfo ReplaceAllBtnInfo
            {
                get
                {
                    return _replaceallbtnInfo;
                }
            }

            /// <summary>
            /// The SkipAllBtn item.
            /// </summary>
            [RepositoryItem("7f2482c8-bd50-4c50-aff9-a6fce719c682")]
            public virtual Ranorex.Button SkipAllBtn
            {
                get
                {
                    return _skipallbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SkipAllBtn item info.
            /// </summary>
            [RepositoryItemInfo("7f2482c8-bd50-4c50-aff9-a6fce719c682")]
            public virtual RepoItemInfo SkipAllBtnInfo
            {
                get
                {
                    return _skipallbtnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
