///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestProduct
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ProjectWindowRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("91b5063c-991e-4569-8a65-1fd9e4489978")]
    public partial class ProjectWindowRepository : RepoGenBaseFolder
    {
        static ProjectWindowRepository instance = new ProjectWindowRepository();
        ProjectWindowRepositoryFolders.ProjectWindowAppFolder _projectwindow;
        ProjectWindowRepositoryFolders.SelectFileAppFolder _selectfile;
        ProjectWindowRepositoryFolders.OpenProjectAppFolder _openproject;
        ProjectWindowRepositoryFolders.ListAppFolder _list;
        ProjectWindowRepositoryFolders.MenuFileAppFolder _menufile;

        /// <summary>
        /// Gets the singleton class instance representing the ProjectWindowRepository element repository.
        /// </summary>
        [RepositoryFolder("91b5063c-991e-4569-8a65-1fd9e4489978")]
        public static ProjectWindowRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ProjectWindowRepository() 
            : base("ProjectWindowRepository", "/", null, 0, false, "91b5063c-991e-4569-8a65-1fd9e4489978", ".\\RepositoryImages\\ProjectWindowRepository91b5063c.rximgres")
        {
            _projectwindow = new ProjectWindowRepositoryFolders.ProjectWindowAppFolder(this);
            _selectfile = new ProjectWindowRepositoryFolders.SelectFileAppFolder(this);
            _openproject = new ProjectWindowRepositoryFolders.OpenProjectAppFolder(this);
            _list = new ProjectWindowRepositoryFolders.ListAppFolder(this);
            _menufile = new ProjectWindowRepositoryFolders.MenuFileAppFolder(this);
        }

#region Variables

        string _ProjectName = "";

        /// <summary>
        /// Gets or sets the value of variable ProjectName.
        /// </summary>
        [TestVariable("356fe602-4bd9-41ee-b3e3-cbb9900b9e82")]
        public string ProjectName
        {
            get { return _ProjectName; }
            set { _ProjectName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("91b5063c-991e-4569-8a65-1fd9e4489978")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProjectWindow folder.
        /// </summary>
        [RepositoryFolder("e449124e-0db5-4931-99c4-8479aabbe103")]
        public virtual ProjectWindowRepositoryFolders.ProjectWindowAppFolder ProjectWindow
        {
            get { return _projectwindow; }
        }

        /// <summary>
        /// The SelectFile folder.
        /// </summary>
        [RepositoryFolder("cb1f8e23-54fc-4b9b-a96a-7e4886684f71")]
        public virtual ProjectWindowRepositoryFolders.SelectFileAppFolder SelectFile
        {
            get { return _selectfile; }
        }

        /// <summary>
        /// The OpenProject folder.
        /// </summary>
        [RepositoryFolder("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
        public virtual ProjectWindowRepositoryFolders.OpenProjectAppFolder OpenProject
        {
            get { return _openproject; }
        }

        /// <summary>
        /// The List folder.
        /// </summary>
        [RepositoryFolder("affa1615-928c-4438-be53-4cb2ac4a956c")]
        public virtual ProjectWindowRepositoryFolders.ListAppFolder List
        {
            get { return _list; }
        }

        /// <summary>
        /// The MenuFile folder.
        /// </summary>
        [RepositoryFolder("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
        public virtual ProjectWindowRepositoryFolders.MenuFileAppFolder MenuFile
        {
            get { return _menufile; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ProjectWindowRepositoryFolders
    {
        /// <summary>
        /// The ProjectWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("e449124e-0db5-4931-99c4-8479aabbe103")]
        public partial class ProjectWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;

            /// <summary>
            /// Creates a new ProjectWindow  folder.
            /// </summary>
            public ProjectWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjectWindow", "/form[@name~'ProjectWindow' and @basetype='QMainWindow']", parentFolder, 30000, null, true, "e449124e-0db5-4931-99c4-8479aabbe103", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "element[@type='ui::MenuBar']/?/?/menuitem[@text='File' and @type='QAction']", "", 30000, null, "7f3bc8e5-16d5-4d28-af2f-712ec810848f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e449124e-0db5-4931-99c4-8479aabbe103")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e449124e-0db5-4931-99c4-8479aabbe103")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("7f3bc8e5-16d5-4d28-af2f-712ec810848f")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("7f3bc8e5-16d5-4d28-af2f-712ec810848f")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }
        }

        /// <summary>
        /// The SelectFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("cb1f8e23-54fc-4b9b-a96a-7e4886684f71")]
        public partial class SelectFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _previouslocationsInfo;
            RepoItemInfo _text41477Info;
            RepoItemInfo _text1148Info;
            RepoItemInfo _openbtnInfo;

            /// <summary>
            /// Creates a new SelectFile  folder.
            /// </summary>
            public SelectFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectFile", "/form[@title='Select Files']", parentFolder, 30000, null, true, "cb1f8e23-54fc-4b9b-a96a-7e4886684f71", "")
            {
                _previouslocationsInfo = new RepoItemInfo(this, "PreviousLocations", "element[@class='WorkerW']//progressbar/toolbar[@class='ToolbarWindow32']/button[@text='Previous Locations']", "", 30000, null, "dc108d39-ce48-4cbc-b391-ed19e860c054");
                _text41477Info = new RepoItemInfo(this, "Text41477", "element[@class='WorkerW']//combobox[@controlid='41477']/text[@controlid='41477']", "", 30000, null, "4d0f4075-4e9c-4d22-b301-2c4deea2bfe1");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", "", 30000, null, "71dd099e-34f1-45a4-a88a-8a482df90b6b");
                _openbtnInfo = new RepoItemInfo(this, "OpenBtn", "button[@text='&Open']", "", 30000, null, "cf4c1e5a-4eed-413c-8c7f-8c8bb0181a14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb1f8e23-54fc-4b9b-a96a-7e4886684f71")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb1f8e23-54fc-4b9b-a96a-7e4886684f71")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PreviousLocations item.
            /// </summary>
            [RepositoryItem("dc108d39-ce48-4cbc-b391-ed19e860c054")]
            public virtual Ranorex.Button PreviousLocations
            {
                get
                {
                    return _previouslocationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PreviousLocations item info.
            /// </summary>
            [RepositoryItemInfo("dc108d39-ce48-4cbc-b391-ed19e860c054")]
            public virtual RepoItemInfo PreviousLocationsInfo
            {
                get
                {
                    return _previouslocationsInfo;
                }
            }

            /// <summary>
            /// The Text41477 item.
            /// </summary>
            [RepositoryItem("4d0f4075-4e9c-4d22-b301-2c4deea2bfe1")]
            public virtual Ranorex.Text Text41477
            {
                get
                {
                    return _text41477Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text41477 item info.
            /// </summary>
            [RepositoryItemInfo("4d0f4075-4e9c-4d22-b301-2c4deea2bfe1")]
            public virtual RepoItemInfo Text41477Info
            {
                get
                {
                    return _text41477Info;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("71dd099e-34f1-45a4-a88a-8a482df90b6b")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("71dd099e-34f1-45a4-a88a-8a482df90b6b")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The OpenBtn item.
            /// </summary>
            [RepositoryItem("cf4c1e5a-4eed-413c-8c7f-8c8bb0181a14")]
            public virtual Ranorex.Button OpenBtn
            {
                get
                {
                    return _openbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenBtn item info.
            /// </summary>
            [RepositoryItemInfo("cf4c1e5a-4eed-413c-8c7f-8c8bb0181a14")]
            public virtual RepoItemInfo OpenBtnInfo
            {
                get
                {
                    return _openbtnInfo;
                }
            }
        }

        /// <summary>
        /// The OpenProjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
        public partial class OpenProjectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _previouslocationsInfo;
            RepoItemInfo _text41477Info;
            RepoItemInfo _text1148Info;
            RepoItemInfo _openbtnInfo;
            RepoItemInfo _combobox1136Info;

            /// <summary>
            /// Creates a new OpenProject  folder.
            /// </summary>
            public OpenProjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenProject", "/form[@title='Open Project']", parentFolder, 30000, null, true, "7846dc71-9b6d-4c80-bfef-f400f97cb875", "")
            {
                _previouslocationsInfo = new RepoItemInfo(this, "PreviousLocations", "element[@class='WorkerW']//progressbar/toolbar[@class='ToolbarWindow32']/button[@text='Previous Locations']", "", 30000, null, "a3cbd65d-a8c7-4c98-98f7-675338fadbb3");
                _text41477Info = new RepoItemInfo(this, "Text41477", "element[@class='WorkerW']//combobox[@controlid='41477']/text[@controlid='41477']", "", 30000, null, "56856e32-e757-4bdf-9ed2-b3b746cd4d30");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", "", 30000, null, "cd7cda52-a63c-4613-8020-050dcfad69cd");
                _openbtnInfo = new RepoItemInfo(this, "OpenBtn", "button[@text='&Open']", "", 30000, null, "288726d3-b25b-403d-93ae-9763d0cc4a8e");
                _combobox1136Info = new RepoItemInfo(this, "ComboBox1136", "combobox[@controlid='1136']", "", 30000, null, "2cf381a7-efba-44b0-b095-aefe916b8eba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7846dc71-9b6d-4c80-bfef-f400f97cb875")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PreviousLocations item.
            /// </summary>
            [RepositoryItem("a3cbd65d-a8c7-4c98-98f7-675338fadbb3")]
            public virtual Ranorex.Button PreviousLocations
            {
                get
                {
                    return _previouslocationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PreviousLocations item info.
            /// </summary>
            [RepositoryItemInfo("a3cbd65d-a8c7-4c98-98f7-675338fadbb3")]
            public virtual RepoItemInfo PreviousLocationsInfo
            {
                get
                {
                    return _previouslocationsInfo;
                }
            }

            /// <summary>
            /// The Text41477 item.
            /// </summary>
            [RepositoryItem("56856e32-e757-4bdf-9ed2-b3b746cd4d30")]
            public virtual Ranorex.Text Text41477
            {
                get
                {
                    return _text41477Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text41477 item info.
            /// </summary>
            [RepositoryItemInfo("56856e32-e757-4bdf-9ed2-b3b746cd4d30")]
            public virtual RepoItemInfo Text41477Info
            {
                get
                {
                    return _text41477Info;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("cd7cda52-a63c-4613-8020-050dcfad69cd")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("cd7cda52-a63c-4613-8020-050dcfad69cd")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The OpenBtn item.
            /// </summary>
            [RepositoryItem("288726d3-b25b-403d-93ae-9763d0cc4a8e")]
            public virtual Ranorex.Button OpenBtn
            {
                get
                {
                    return _openbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenBtn item info.
            /// </summary>
            [RepositoryItemInfo("288726d3-b25b-403d-93ae-9763d0cc4a8e")]
            public virtual RepoItemInfo OpenBtnInfo
            {
                get
                {
                    return _openbtnInfo;
                }
            }

            /// <summary>
            /// The ComboBox1136 item.
            /// </summary>
            [RepositoryItem("2cf381a7-efba-44b0-b095-aefe916b8eba")]
            public virtual Ranorex.ComboBox ComboBox1136
            {
                get
                {
                    return _combobox1136Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1136 item info.
            /// </summary>
            [RepositoryItemInfo("2cf381a7-efba-44b0-b095-aefe916b8eba")]
            public virtual RepoItemInfo ComboBox1136Info
            {
                get
                {
                    return _combobox1136Info;
                }
            }
        }

        /// <summary>
        /// The ListAppFolder folder.
        /// </summary>
        [RepositoryFolder("affa1615-928c-4438-be53-4cb2ac4a956c")]
        public partial class ListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _allfilesInfo;

            /// <summary>
            /// Creates a new List  folder.
            /// </summary>
            public ListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("List", "/list[@controlid='1000']", parentFolder, 30000, null, true, "affa1615-928c-4438-be53-4cb2ac4a956c", "")
            {
                _allfilesInfo = new RepoItemInfo(this, "AllFiles", "listitem[@text~'All']", "", 30000, null, "43dc5d30-1806-4e09-9b09-a08a72cdf0c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("affa1615-928c-4438-be53-4cb2ac4a956c")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("affa1615-928c-4438-be53-4cb2ac4a956c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllFiles item.
            /// </summary>
            [RepositoryItem("43dc5d30-1806-4e09-9b09-a08a72cdf0c3")]
            public virtual Ranorex.ListItem AllFiles
            {
                get
                {
                    return _allfilesInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AllFiles item info.
            /// </summary>
            [RepositoryItemInfo("43dc5d30-1806-4e09-9b09-a08a72cdf0c3")]
            public virtual RepoItemInfo AllFilesInfo
            {
                get
                {
                    return _allfilesInfo;
                }
            }
        }

        /// <summary>
        /// The MenuFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
        public partial class MenuFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;

            /// <summary>
            /// Creates a new MenuFile  folder.
            /// </summary>
            public MenuFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuFile", "/contextmenu[@name='menuFile']", parentFolder, 30000, null, true, "ab54eb33-74a5-4a50-bb2a-e0867116844b", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "menuitem[@name='actOpen']", "", 30000, null, "a1980d2b-d26c-4e3f-9d96-bff6c7081d5d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab54eb33-74a5-4a50-bb2a-e0867116844b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("a1980d2b-d26c-4e3f-9d96-bff6c7081d5d")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("a1980d2b-d26c-4e3f-9d96-bff6c7081d5d")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
