///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TEARDOWN
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TEARDOWNRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5d41cd6a-52d6-4352-9310-43b487a1d714")]
    public partial class TEARDOWNRepository : RepoGenBaseFolder
    {
        static TEARDOWNRepository instance = new TEARDOWNRepository();
        TEARDOWNRepositoryFolders.ProjectWindowAppFolder _projectwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TEARDOWNRepository element repository.
        /// </summary>
        [RepositoryFolder("5d41cd6a-52d6-4352-9310-43b487a1d714")]
        public static TEARDOWNRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TEARDOWNRepository() 
            : base("TEARDOWNRepository", "/", null, 0, false, "5d41cd6a-52d6-4352-9310-43b487a1d714", ".\\RepositoryImages\\TEARDOWNRepository5d41cd6a.rximgres")
        {
            _projectwindow = new TEARDOWNRepositoryFolders.ProjectWindowAppFolder(this);
        }

#region Variables

        string _columnID = "0";

        /// <summary>
        /// Gets or sets the value of variable columnID.
        /// </summary>
        [TestVariable("3b6f8db5-c789-4ae1-b52a-c0420255fd19")]
        public string columnID
        {
            get { return _columnID; }
            set { _columnID = value; }
        }

        string _rowID = "0";

        /// <summary>
        /// Gets or sets the value of variable rowID.
        /// </summary>
        [TestVariable("d7e68b10-bade-443e-8df2-63a01028a15d")]
        public string rowID
        {
            get { return _rowID; }
            set { _rowID = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5d41cd6a-52d6-4352-9310-43b487a1d714")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProjectWindow folder.
        /// </summary>
        [RepositoryFolder("3662a38e-71ee-45f1-9923-847fba9fbb81")]
        public virtual TEARDOWNRepositoryFolders.ProjectWindowAppFolder ProjectWindow
        {
            get { return _projectwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TEARDOWNRepositoryFolders
    {
        /// <summary>
        /// The ProjectWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("3662a38e-71ee-45f1-9923-847fba9fbb81")]
        public partial class ProjectWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new ProjectWindow  folder.
            /// </summary>
            public ProjectWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProjectWindow", "/form[@name='ProjectWindow']", parentFolder, 30000, null, true, "3662a38e-71ee-45f1-9923-847fba9fbb81", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "element[@type='ui::MenuBar']/?/?/menuitem[@text='File']", "", 30000, null, "a975bca5-0616-4936-85ca-2e2f9784746e");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close' and @accessiblerole='PushButton']", "", 30000, null, "187ba548-55c8-4095-aa16-632bc2e33385");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3662a38e-71ee-45f1-9923-847fba9fbb81")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3662a38e-71ee-45f1-9923-847fba9fbb81")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("a975bca5-0616-4936-85ca-2e2f9784746e")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("a975bca5-0616-4936-85ca-2e2f9784746e")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("187ba548-55c8-4095-aa16-632bc2e33385")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("187ba548-55c8-4095-aa16-632bc2e33385")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
